// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dliebicltvrzenpluoxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsaWViaWNsdHZyemVucGx1b3hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg5OTI2MzcsImV4cCI6MjA4NDU2ODYzN30.RIZ4TNfauLk7P9nVllUhhb40KbFNlhLboYSRTjtVlx0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});